export enum AllModelsType {
  STATE_SKY_MODEL = 'StateSkyModel',
  TEMPERATURE_MODEL = 'TemperatureModel',
  TEMPERATURES_MODEL = 'TemperaturesModel',
  CITY_MODEL = 'CityModel',
  CITIES_MODEL = 'CitiesModel',
  COMAUTONOMA_MODEL = 'ComautonomaModel',
  BREADCRUM_MODEL = 'BreadcrumModel',
  BREADCRUMS_MODEL = 'BreadcrumsModel',
  SINGLE_PROVINCE_MODEL = 'SingleProvinceModel',
  PROVINCE_MODEL = 'ProvinceModel',
  PROVINCES_MODEL = 'ProvincesModel',
  ALL_PROVINCES_MODEL = 'AllProvincesModel',
  ITEM_MODEL = 'ItemModel',
  DATA_LIST_MODEL = 'DataListModel',
}
